addSbtPlugin("org.scala-js" % "sbt-scalajs"  % "0.6.16")
addSbtPlugin("io.spray"     % "sbt-revolver" % "0.8.0")
addSbtPlugin("com.lihaoyi"  % "workbench"    % "0.3.0")
addSbtPlugin("com.vmunier"  % "sbt-web-scalajs" % "1.0.3")
addSbtPlugin("com.typesafe.sbt" % "sbt-web" % "1.4.0")